name: example
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: prepare raku
      run: |
        $env:PATH += ";C:/strawberry/c/bin;C:/strawberry/perl/site/bin;C:/strawberry/perl/bin"
        $env:GIT_TRACE_PACKET = 1
        $env:GIT_TRACE = 1
        $env:GIT_CURL_VERBOSE = 1
        cpan "Locale::Maketext::Simple"
        mkdir C:\work
        cd C:\work 
        git --version
        git clone --verbose "git@github.com:rakudo/rakudo.git" rakudo
        cd rakudo
        perl Configure.pl --gen-moar --gen-nqp --backends=moar
        nmake install
        SET PATH="C:\work\rakudo\install\share\perl6\site\bin;C:\work\rakudo\install\bin;%PATH%"
        cd C:\work
    - name: install zef
      run: |
        perl6 -v



