name: example
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: set path
      run: setx /M PATH "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;${env:PATH}";
    - name: install perl deps
      run: cd c:\strawberry\c\bin; dir #c:\strawberry\c\bin\cpan.bat "Locale::Maketext::Simple"
    - name: set up dirs
      run: mkdir C:\work
    - name: checkout rakudo
      run: git clone --verbose "https://github.com/rakudo/rakudo.git" c:\work\rakudo
    - name: configure
      run: cd c:\work\rakudo; perl Configure.pl --gen-moar --gen-nqp --backends=moar
    - name: make/install
      run: cd c:\work\rakudol nmake install
#
#          cd rakudo;
#          perl Configure.pl --gen-moar --gen-nqp --backends=moar;
#          nmake install;
#          SET PATH="C:\work\rakudo\install\share\perl6\site\bin;C:\work\rakudo\install\bin;%PATH%";
#          cd C:\work;
    - name: install zef
      run: |
        perl6 -v



